### ISSUE TITLE
Logging Backend v0.11.1 install fails when both ephemeral storage and a single Primary Pod are configured

### ISSUE THREAD

**Issue by ron1** [rancher/opni#1695]
Logging Backend install using v0.11.1 fails when both ephemeral storage and a single Primary Pod are configured. The specific error is included below:

[403 Forbidden] {"error":{"root_cause":[{"type":"security_exception","reason":"no permissions for [cluster:monitor/task/get] and User [name=internalopni, backend_roles=[], requestedTenant=null]"}],"type":"security_exception","reason":"no permissions for [cluster:monitor/task/get] and User [name=internalopni, backend_roles=[], requestedTenant=null]"},"status":403}: opensearch request unsuccessful

**Comment by dbason** [comment]
I believe this specific issue is caused by a partially completed uninstall with data delete.  I have some ideas about how we can make this more robust.

**Comment by ron1** [comment]
According to https://gitlab.com/sylva-projects/sylva-core/-/blob/capo-ci-test-opni-sylva-integration/docs/opni.md?ref_type=heads#opni-logging-backend-controlplane-configuration, it seems the Project Sylva folks already encountered this issue. Their recommended workaround is to set the number of Primary Pods to a value >= 3. This suggestion worked for me as well.

@dbason Any ideas why this workaround seems to resolve the problem?

I don't think the problem is related to a partially completed uninstall.

**Comment by dbason** [comment]
Sorry I think I'm conflating this with the discussions we had yesterday.  That issue is related to incomplete uninstall where delete data is set to true.

I think I know what is going on; but it would only impact the cluster if there is not PVC attached to the data pod.  Once the cluster is initialized the operator updates it to remove the bootstrap pod, which results in the pods being redeployed.  If there is only one data pod then the security index will be lost.  I think this is solvable in the upstream operator, but will require some more conditional logic around setting up the cluster.

The primary/data pods should be set to >=2 if there is no persistent storage attached to the cluster regardless though otherwise you will always be at risk of data loss.

**Comment by ron1** [comment]
Ahhh...that explains it. I didn't realize that the Logging Config "Persistent" field is actually a checkbox that when checked would enable the use of PVC's and the Storage Class field.

It seems my current default Logging configuration specifies Ephemeral Storage w/1 Replica which is non-functional. Until the necessary Opster changes are implemented, it would be nice to prevent users from specifying this non-functional configuration. It should definitely not be proposed as a default configuration.

I'll try reconfiguring my Logging Backend with a single PVC and confirm it works for me as well.

**Comment by dbason** [comment]
https://github.com/rancher/opni/pull/1701 will update the default primary pod replicas to 2.  I think this is the cleanest solution to this problem.

**Comment by ron1** [comment]
Makes sense. Would it also make sense for the validation to protect against known invalid configurations? For example, I could envision replicas being manually lowered to 1 in a resource constrained environment which would unknowingly cause harm.
