### ISSUE TITLE
how to setup proxy when install opni-inference-control-plane 

### ISSUE THREAD

**Issue by 24237805** [rancher/opni#176]
currently facing issue when install opni-inference-control, I check the logs 
```
Error from server (BadRequest): container "inference-service" in pod "opni-inference-control-plane-586d857f5b-kgn6d" is waiting to start: PodInitializing
```
I suspect can't download the https://opni-public.s3.us-east-2.amazonaws.com/pretrain-models/control-plane-model-v0.1.2.zip, maybe need proxy, but I don't know how to add proxy, could you give some suggestions, thanks!

**Comment by dbason** [comment]
Currently there are no proxy options, but there are a couple of alternative ways to get the model.

You could download that file and self host it at an http endpoint inside your organization.  You can then change the [URL](https://opni.io/configuration/pretrainedmodel/#httpsource) in the pretrained model config to point at that.

The other option is build the model into an OCI image.  The model zip file should be in `/staging/modelname.zip` in the image.  Then rather than using the http config for the pretrained model you can use a [container source](https://opni.io/configuration/pretrainedmodel/#modelsource)

**Comment by 24237805** [comment]
thanks @dbason , I will try that, currently my workaround is use kubectl edit command, just add the proxy into deployment, and pod can run correctly
