### ISSUE TITLE
Opni branding in OpenSearch

### ISSUE THREAD

**Issue by sanjay920** [rancher/opni#343]
Will include the opni logo as per https://opensearch.org/docs/latest/dashboards/branding/

**Comment by dbason** [comment]
The dashboards branding requires the images to be hosted on the web rather than locally in the image.  If the image URLs are unavailable then the UI will revert to default branding.  This means that airgapped clusters will still have default branding.

This also requires additional config options in the opensearch operator to allow the config options to parking this until that work is done.
