### ISSUE TITLE
minio helm chart removed

### ISSUE THREAD

**Issue by zoopster** [rancher/opni#85]
opnictl demo fails on the minio chart
the helm.min.io chart repo has been archived in favor of using the minio operator. Any chance to get it updated  to use https://github.com/minio/operator/tree/master/helm/minio-operator ?

**Comment by kralicky** [comment]
Unfortunately we can't use the minio operator due to its license. We are working on a better way to manage our deployments instead of using helm charts, but in the mean time the existing helm chart should still work. If you are using a k8s distro that does not bundle the helm controller, make sure to enter "Y" when `opnictl create demo` asks if you want to install it.

**Comment by zoopster** [comment]
I'll close this then until I can reproduce...it just may well be how the demo was being created.
