### ISSUE TITLE
Naming a new cluster causes overwrites the name of existing cluster

### ISSUE THREAD

**Issue by codyrancher** [rancher/opni#965]
We don't have a consistent repro for this issue yet. 

There is one theory for the cause:

1. On the cluster page we poll the list of clusters until a new one is created and assume the newest one is the one the user on the page created.
2.  We then use that cluster we assume the user created and apply the name and labels.
3.  This assumption isn't always going to be correct and can lead to the names and labels being applied to the wrong cluster.

We need to have a way to find out which cluster was created with a particular command.

**Comment by codyrancher** [comment]
Here are some possible solutions @kralicky and I discussed a while back:
- Store and return the token id the cluster was created wtih?
- Pass an additional id or token as a part of the command that gets stored as a label in the cluster
- Tweak the token format to include the above

**Comment by kralicky** [comment]
1. Store and return the token id the cluster was created with
	* if you add two clusters with the same token, they would both show up as having been created with that token, and you could potentially end up overwriting the name of one of them
2. Pass an additional id or token as a part of the command that gets stored as a label in the cluster
	* clusters can't edit their own labels, so this might not work. the labels are associated with the token on the server side
3. Tweak the token format to include the above
	* this might work, but I think there are more advantages to keeping the token payload opaque.

I propose we introduce a new internal label `opni.io/name-template` that will be attached to tokens and will be edited by the UI while the user is going through the new cluster dialog. This label will be a _template_ for a cluster name created with this token. The template can support a few built in variables, such as 
	- `${hostname}` (substitutes the kubernetes.io/hostname node label) 
	- `${instanceType}` (substitutes the node.kubernetes.io/instance-type node label) 
	- `${count}` (current token usage count)
	- `${random}` (random adjective-noun name)
This means the UI doesn't have to set the labels when it sees the cluster join (which is kind of hacky anyway), instead the labels are set automatically by the gateway, and this also allows reusable tokens, since it is only storing a name template instead of the exact name that will be used.
A sample/default name template could be something like `${hostname}-${instanceType}` or just `${random}`.

**Comment by sanjay920** [comment]
sgtm. Target date for this to be developed and tested? @kralicky

**Comment by codyrancher** [comment]
I don't think this suggestion is sufficient. We also add labels to the cluster unless you also want to add a opni.io/labels label that we set while creating the cluster.

**Comment by dbason** [comment]
As discussed on Slack we shouldn't be depending on the UI to make changes.  I think the friendly name should be a specific part of the data stored with the cluster.  Then we have two options, we can have the user prepopulate the cluster (similar to how Rancher does it for custom clusters getting imported) or it can be an additional variable in the add cluster command so it will get added when the cluster bootstraps.

**Comment by dbason** [comment]
In the short term we can add a field to the bootstrap command to allow the name label to be passed in.  This will not enforce uniqueness of the name or allow it to be discoverable.

Longer term we need to understand the implications of moving the name to a field in the cluster schema.  This will allow us to enforce constraints and discover the cluster based on names but will have wide blast radius.

**Comment by kralicky** [comment]
https://github.com/rancher/opni/pull/1002
